### ISSUE TITLE
Capture moves aren't working on the front-end

### ISSUE THREAD

**Issue by icrustandi** [fire-cakes/pancakes#43]
** they are working, but not reliably. I have to click several times back and forth for the capture and move to execute.

**Comment by danielpowell4** [comment]
The real fix will be implementing draggable and droppable jQuery UI

Otherwise you have to click the corner of the piece being attacked (not the piece itself)

**Comment by icrustandi** [comment]
Oh interesting. Basically clicking anywhere but the piece works. Is that because it's not differentiating between a mouse click that is selecting a piece to move and a mouse click that wants to move to that destination?

**Comment by danielpowell4** [comment]
Correct. 

If you click on any piece, the simple jQuery "thinks" that you are then going to try and move that piece--rather than take it.

**Comment by icrustandi** [comment]
Thanks, that clarifies a lot. I was trying to figure out why the behavior wasn't consistent. Turns out I was also clicking inconsistently :p

**Comment by danielpowell4** [comment]
Totally makes sense. It is a little weird. When I was working on it, I just wanted to get an MVP working.

Setting up draggable and droppable wouldn't be **TOO** difficult, you'd just have to rearrange which events collect data attributes and, maybe, how the ajax call gets made.

**Comment by icrustandi** [comment]
Yeah, it doesn't seem too bad. Looks easy enough from this resource: https://jqueryui.com/droppable/
I'll give it a try once I have time

**Comment by icrustandi** [comment]
Added draggable/droppable!
